# Generated by Django 3.2.3 on 2021-05-27 14:21

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(null=True, upload_to=status.models.upload_status_image),
        ),
    ]
